############################################
#### LIGHTS
############################################


- platform: rfxtrx
  automatic_add: false

- platform: hue
  host: 192.168.1.44
  filename: phue.conf

#- platform: yeelight
#  devices:
#    192.168.7.117:
#      name: Lampa ytterdörren
#      transition: 1000
#      use_music_mode: False
#      save_on_change: False