############################################
#### SENSORS
############################################


- platform: rfxtrx
  automatic_add: True
  devices:
    08500704970000c059:
      name: kontor
    08500704a800801859:
      name: moas_rum_ute
    0a520902b70000ec240259:
      name: sovrum
      data_type:
       - Humidity
       - Temperature
    0a520902c70000df2b0159:
      name: allrum
      data_type:
       - Humidity
       - Temperature
    0a520902a70000ea260259:
      name: moas_rum
      data_type:
       - Humidity
       - Temperature

- platform: cert_expiry
  host: hassio37.duckdns.org

#sensor.myiphone:
#  friendly_name: iPhone Battery
#  homebridge_hidden: true
#  unit_of_measurement: '%'


# Weather prediction
- platform: yr
  name: Weather
  forecast: 24
  monitored_conditions:
    - temperature
    - symbol
    - precipitation
    - windSpeed
    - pressure
    - windDirection
    - humidity
    - fog
    - cloudiness
    - lowClouds
    - mediumClouds
    - highClouds
    - dewpointTemperature

- platform: wunderground
  api_key: !secret wunderground_api_key
  monitored_conditions:
    - temp_high_record_c
    - temp_high_1d_c
    - temp_c
    - temp_low_1d_c
    - temp_low_record_c
    - precip_1d
    - precip_1d_mm
    - wind_kph
    - wind_1d_kph
    - alerts
    - UV